#!/bin/bash
set -e
# POTCAR generation script
# Generated by VASPilot with vasp-potcar-skill recommendations
# POTCAR_DIR on HPC must match config hpc.potcar_dir (e.g. /public/home/wenliyang/atomate/potcar_ori/POT_GGA_PAW_PBE_54)

POTCAR_DIR="/public/home/wenliyang/atomate/potcar_ori/POT_GGA_PAW_PBE_54"
OUTPUT="POTCAR"

rm -f "$OUTPUT"


# Si -> Si
if [ -f "$POTCAR_DIR/Si/POTCAR" ]; then
    cat "$POTCAR_DIR/Si/POTCAR" >> "$OUTPUT"
elif [ -f "$POTCAR_DIR/Si/POTCAR.gz" ]; then
    zcat "$POTCAR_DIR/Si/POTCAR.gz" >> "$OUTPUT"
elif [ -f "$POTCAR_DIR/POTCAR.Si" ]; then
    cat "$POTCAR_DIR/POTCAR.Si" >> "$OUTPUT"
elif [ -f "$POTCAR_DIR/POTCAR.Si.gz" ]; then
    zcat "$POTCAR_DIR/POTCAR.Si.gz" >> "$OUTPUT"
else
    echo "ERROR: POTCAR for Si not found in $POTCAR_DIR"
    exit 1
fi

echo "POTCAR generated successfully: $OUTPUT"
echo "Elements: Si"
